title: サイトのタイトル
email: your-email@example.com
description: >- 
  多端末・多言語サイト構成
url: "https://ai-chie.github.io/"
baseurl: "" # ルートの場合は空に。サブディレクトリに配置する場合は設定（例: /blog）
logo:
search: false # true, false (default)
search_full_content: false # true, false (default)
search_provider: lunr # lunr (default), algolia
algolia:
  application_id: # YOUR_APPLICATION_ID
  index_name: # YOUR_INDEX_NAME
  search_only_api_key: # YOUR_SEARCH_ONLY_API_KEY
  powered_by: # true (default), false

# Markdownエンジン
markdown: kramdown
# highlighter: rouge
# theme: minima
# プラグイン（GitHub Pages 互換性を保つものを使用）
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
#  - jekyll-include-cache
feed:
  path: atom.xml

# ページネーション（必要であれば有効化）
paginate: 10
paginate_path: "/page:num"

# ビルド対象のディレクトリ
source: .
destination: ./_site

# Exclude（ビルド対象から除外）
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock 
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/  
  - .github/
  - _admin/
  - _export/
  - _log/
  - _proj_mgmt/
  - _scripts/
  - docs/
  - .gitattributes
  - .gitignore
  - README.md

# Include（明示的に処理対象とするディレクトリ）
include:
  - _data/
  - _includes/
  - _layouts/
  - _pages/
  - _posts/
  - assets/
  - .htaccess
  - index.md
  - index.html
  - robots.txt
  - sitemap.xml
  - sitemap_text.xm
#  - _generated

timezone: Asia/Tokyo

encoding: utf-8

show_drafts: false

future: false

unpublished: false

lsi: true



permalink: 

# データ・レイアウトなどの読み込み
layouts_dir: _layouts
includes_dir: _includes
data_dir: _data
# collections_dir: _collections

# 投稿と記事
defaults:
  # 日本語コンテンツ全般
  - scope:
      path: "ja"
    values:
      lang: "ja"
      layout: default

  # 英語コンテンツ全般
  - scope:
      path: "en"
    values:
      lang: "en"
      layout: default

  # 投稿全体（_posts配下）への初期値（明示的な draft/hidden 対応）
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      permalink: /:categories/:title/
      lang: ja
      draft: false
      hidden: false
  - scope:
      path: "_posts/ja"
    values:
      lang: ja
  - scope:
      path: "_posts/en"
    values:
      lang: en


# 言語対応設定
languages: ["ja", "en"]
default_lang: "ja"

# GitHub Pages 対応（project pageでない場合は false）
github:
  is_project_page: false

#------------------
#title: あなたのサイト名
#description: あなたのサイトの説明
#baseurl: "" # サブディレクトリに設置する場合は例: /blog
#url: "https://ai-chie.github.io/" # ご自身のドメインに変更
#
## Markdown / テンプレートエンジン
#markdown: kramdown
#highlighter: rouge
#
## 出力対象に含めるフォルダ（通常は処理されない）
#include:
#  - _generated
#
## 除外対象（ビルドしないファイルやディレクトリ）
#exclude:
#  - node_modules
#  - vendor
#  - README.md
#  - Gemfile
#  - Gemfile.lock
#  - .github
#  - .gitignore
#
## プラグイン（GitHub Pages上で使えるものは限定）
#plugins: []
#
## デフォルト値の適用（投稿・カテゴリ・タグで共通化）
#defaults:
#  # 日本語コンテンツ全般
#  - scope:
#      path: "ja"
#    values:
#      lang: "ja"
#      layout: default
#
#  # 英語コンテンツ全般
#  - scope:
#      path: "en"
#    values:
#      lang: "en"
#      layout: default
#
#  # 投稿全体（_posts配下）への初期値（明示的な draft/hidden 対応）
#  - scope:
#      path: ""
#      type: "posts"
#    values:
#      draft: false
#      hidden: false
#
## ページネーション（必要であれば有効化）
# paginate: 10
# paginate_path: "/page:num"

#------------------
#title: あなたのサイト名
#description: あなたのサイトの説明
#baseurl: "" # サブディレクトリに配置する場合は設定（例: /blog）
#url: "https://ai-chie.github.io/" # あなたのドメインに置き換えてください
#
# ディレクトリ設定
#collections:
#  posts:
#    output: true
#
## ページ出力対象に含めるファイル／ディレクトリ
#include:
#  - _generated
#
## 除外（不要ファイルなど）
#exclude:
#  - node_modules
#  - vendor
#  - README.md
#  - Gemfile
#  - Gemfile.lock
#  - .github
#  - .gitignore
#
## Markdown & テンプレートエンジン設定
#markdown: kramdown
#highlighter: rouge
#
## プラグイン（GitHub Pages 互換性を保つため、基本的には空でもOK）
#plugins: []
#
## ローカリゼーション・カスタム変数（任意）
#defaults:
#  -
#    scope:
#      path: ""
#      type: "posts"
#    values:
#      layout: "post"
#      lang: "ja"
#
## カスタム変数（必要に応じて）
#paginate: 10
#paginate_path: "/page:num"

#------------------
#title: My MultiLang Site
#baseurl: "" # GitHub Pagesでルートに置く場合
#url: "https://ai-chie.github.io/"
#markdown: kramdown
#theme: minima
#defaults:
#  - scope:
#      path: ""
#    values:
#      layout: default
#collections:
#  posts:
#    output: true
#    permalink: /:collection/:path/
#plugins:
#  - jekyll-feed
#exclude:
#  - Gemfile
#  - Gemfile.lock
#  - node_modules
#  - vendor

#------------------
#plugins:
#  - jekyll-sitemap
