title: サイトのタイトル
email: your-email@example.com
description: >- 
  多端末・多言語サイト構成
url: "https://ai-chie.github.io/"
baseurl: "" # ルートの場合は空に。サブディレクトリに配置する場合は設定（例: /blog）
logo:
search: false # true, false (default)
search_full_content: false # true, false (default)
search_provider: lunr # lunr (default), algolia
algolia:
  application_id: # YOUR_APPLICATION_ID
  index_name: # YOUR_INDEX_NAME
  search_only_api_key: # YOUR_SEARCH_ONLY_API_KEY
  powered_by: # true (default), false

# Markdownエンジン
markdown: kramdown
# highlighter: rouge
# theme: minima
# プラグイン（GitHub Pages 互換性を保つものを使用）
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
#  - jekyll-include-cache
feed:
  path: atom.xml

# ページネーション（必要であれば有効化）
paginate: 10
paginate_path: "/page:num"

# ビルド対象のディレクトリ
source: .
destination: ./_site

# Exclude（ビルド対象から除外）
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock 
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/  
  - .github/
  - _admin/
  - _export/
  - _log/
  - _proj_mgmt/
  - _scripts/
  - docs/
  - .gitattributes
  - .gitignore
  - README.md
  - _posts/

# Include（明示的に処理対象とするディレクトリ）
include:
  - _data/
  - _includes/
  - _layouts/
  - _pages/
#  - _posts/
  - assets/
  - .htaccess
  - index.md
  - index.html
  - robots.txt
  - sitemap.xml
  - sitemap_text.xm
#  - _generated

timezone: Asia/Tokyo
encoding: utf-8
show_drafts: false
future: false
unpublished: false
lsi: true

# permalink: 
  
# collections_dir: _collections

# ディレクトリ設定
# collections:
#  posts:
#    output: true
#    permalink: /:collection/:path/

# GitHub Pages 対応（project pageでない場合は false）
github:
  is_project_page: false

canonical:
  enabled: true                # ← 全体ON/OFF。canonical出力を有効化
  base_device: "pc"            # 正規URLとして使う device。canonicalを統一する対象の device（例: "pc"）
  override_allowed: true       # Front Matterでの canonical_override を許可。page.canonical_override による上書きを許可
  fallback_to_base: true       # per_lang にない言語は base_device/lang を使う
  per_lang:                    # 言語別canonicalルート（省略時は base_device 使用）
    ja: "/pc/ja"
    en: "/pc/en"


# 言語対応設定
# languages: ["ja", "en"]
# default_lang: "ja"

# 以下の理由によりdefaults:は設定しない。
# _pages/はスクリプトにより出力展開される。
# device, lang, type, layout, permalinkはスクリプトにより出力展開される際にcalculatedされる。
# スクリプトにより出力展開される際に投稿やtaxonomyのスキーマ定義や各taxonomyの定義ファイル（categories.yml, tags.yml）によりデフォルト補完が行われる
# defaults:
## device:
#   - scope:
#       path: "_pages/pc/"
#       type: "pages"
#     values:
#       device: "pc"      
#   - scope:
#       path: "_pages/mobile/"
#       type: "pages"
#     values:
#       device: "mobile"      
#   - scope:
#       path: "_pages/text/"
#       type: "pages"
#     values:
#       device: "text"      
## lang
#   - scope:
#       path: "*/ja"
#       type: "pages"
#     values:
#       lang: "ja"
#   - scope:
#       path: "*/en"
#       type: "pages"
#     values:
#       lang: "en"

# 以下は例示
  # 投稿全体（_posts配下）への初期値（明示的な draft/hidden 対応）
# defaults:
#   - scope:
#       path: ""
#       type: "posts"
#     values:
#       layout: post
#       permalink: /:categories/:title/
#       lang: ja
#       draft: false
#       hidden: false

#   - scope:
#       path: ""
#     values:
#       layout: default
