title: GPTとの対話記録
layout: home
description: noteの代わりに記録を残すアーカイブサイト
baseurl: ""
url: "https://ai-chie.github.io"
theme: minima

markdown: kramdown
permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-feed
  - jekyll-seo-tag

sass:
  style: compressed
