title: My MultiLang Site
baseurl: "" # GitHub Pagesでルートに置く場合
url: "https://ai-chie.github.io/"
markdown: kramdown
theme: minima
defaults:
  - scope:
      path: ""
    values:
      layout: default
collections:
  posts:
    output: true
    permalink: /:collection/:path/
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

#plugins:
#  - jekyll-sitemap
