title: サイトのタイトル
email: your-email@example.com
description: >- 
  多端末・多言語サイト構成
url: "https://ai-chie.github.io/"
baseurl: "" # ルートの場合は空に。サブディレクトリに配置する場合は設定（例: /blog）
logo:
search: false # true, false (default)
search_full_content: false # true, false (default)
search_provider: lunr # lunr (default), algolia
algolia:
  application_id: # YOUR_APPLICATION_ID
  index_name: # YOUR_INDEX_NAME
  search_only_api_key: # YOUR_SEARCH_ONLY_API_KEY
  powered_by: # true (default), false

# Markdownエンジン
markdown: kramdown
# highlighter: rouge
# theme: minima
# プラグイン（GitHub Pages 互換性を保つものを使用）
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
#  - jekyll-include-cache
feed:
  path: atom.xml

# ページネーション（必要であれば有効化）
paginate: 10
paginate_path: "/page:num"

# ビルド対象のディレクトリ
source: .
destination: ./_site

# Exclude（ビルド対象から除外）
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock 
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/  
  - .github/
  - _admin/
  - _export/
  - _log/
  - _proj_mgmt/
  - _scripts/
  - docs/
  - .gitattributes
  - .gitignore
  - README.md

# Include（明示的に処理対象とするディレクトリ）
include:
  - _data/
  - _includes/
  - _layouts/
  - _pages/
  - _posts/
  - assets/
  - .htaccess
  - index.md
  - index.html
  - robots.txt
  - sitemap.xml
  - sitemap_text.xm
#  - _generated

timezone: Asia/Tokyo

encoding: utf-8

show_drafts: false

future: false

unpublished: false

lsi: true

# permalink: 
# collections_dir: _collections

# ディレクトリ設定
#collections:
#  posts:
#    output: true

# GitHub Pages 対応（project pageでない場合は false）
github:
  is_project_page: false

# 言語対応設定
languages: ["ja", "en"]
default_lang: "ja"

# 投稿と記事
defaults:
  # 日本語コンテンツ全般
  - scope:
      path: "ja"
    values:
      lang: "ja"
      layout: default

  # 英語コンテンツ全般
  - scope:
      path: "en"
    values:
      lang: "en"
      layout: default

  # 投稿全体（_posts配下）への初期値（明示的な draft/hidden 対応）
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      permalink: /:categories/:title/
      lang: ja
      draft: false
      hidden: false
  - scope:
      path: "_posts/ja"
    values:
      lang: ja
  - scope:
      path: "_posts/en"
    values:
      lang: en


## デフォルト値の適用（投稿・カテゴリ・タグで共通化）
#defaults:
#  # 日本語コンテンツ全般
#  - scope:
#      path: "ja"
#    values:
#      lang: "ja"
#      layout: default
#
#  # 英語コンテンツ全般
#  - scope:
#      path: "en"
#    values:
#      lang: "en"
#      layout: default
#
#  # 投稿全体（_posts配下）への初期値（明示的な draft/hidden 対応）
#  - scope:
#      path: ""
#      type: "posts"
#    values:
#      draft: false
#      hidden: false
#
## ローカリゼーション・カスタム変数（任意）
#defaults:
#  -
#    scope:
#      path: ""
#      type: "posts"
#    values:
#      layout: "post"
#      lang: "ja"
#

#defaults:
#  - scope:
#      path: ""
#    values:
#      layout: default
#collections:
#  posts:
#    output: true
#    permalink: /:collection/:path/

