lang: ja
device: text

# 出力ディレクトリ
destination: ./_site

# デフォルト設定（text専用）
defaults:
  - scope:
      path: ""
    values:
      layout: text
      device: text
      lang: ja

# プラグイン（GitHub Pages互換）
plugins:
  - jekyll-feed
  - jekyll-sitemap

# text 構成のルートページ群
include:
  - _pages
  - _generated
  - _data
  - _includes
  - _layouts

# 除外（ビルド対象外）
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - .github
  - _scripts
  - _posts
  - _proj-mgmt
  - .gitignore
  - node_modules
  - vendor

# SEO関連
title: "AI向け構造化テキストページ"
description: "AIと検索エンジンのための軽量・構造化Jekyllページ"
url: "https://ai-chie.github.io"
baseurl: ""

# 言語
languages: ["ja", "en"]
default_lang: "ja"
