name: Generate Taxonomy Pages

on:
  push:
    paths:
      - '_posts/**'
      - '_data/taxonomy/schema.yml'
      - '_scripts/generate_taxonomy_pages_full.rb'
      - '.github/workflows/generate-taxonomy.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install dependencies
        run: |
          gem install i18n
          gem install yaml

      - name: Run taxonomy generation script
        run: ruby _scripts/generate_taxonomy_pages_full.rb

      - name: Show output logs
        run: |
          echo "== Generated Slugs =="
          cat _log/generated_slugs.yml || echo "No slugs generated."
          echo "== Missing Overrides =="
          cat _data/missing_slug_overrides.yml || echo "No missing overrides."
          echo "== Duplicate Slugs =="
          cat _log/duplicate_slugs.yml || echo "No duplicates found."

      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add _generated/ _data/generated_taxonomy.yml _data/missing_slug_overrides.yml _log/
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto-generate taxonomy data and logs"
          git push
