defaults:
  description: "このサイトはAI・多言語・多端末に対応した情報発信を行うプロジェクトです。" # ← サイト全体の説明文
  image: "/assets/img/default-og-image.png" # ← SNSカードや構造化データのOG画像
  author: "AI-Chie Project" # ← schema.org用の著者名
  lang: "ja" # ← 未指定時の言語既定
  theme_color: "#ffffff"

robots:
  default: "index, follow"
  exclude_paths: # ← noindexにしたいパスのリスト
    - /search/
    - /404.html

# canonical.htmlのロジック制御用
canonical:
  enabled: true                # ← 全体ON/OFF。canonical出力を有効化
  base_device: "pc"            # 正規URLとして使う device。canonicalを統一する対象の device（例: "pc"）
  override_allowed: true       # Front Matterでの canonical_override を許可。page.canonical_override による上書きを許可
  fallback_to_base: true       # per_lang にない言語は base_device/lang を使う
  per_lang:                    # ← 言語別canonical正規パス。言語別canonicalルート（省略時は base_device 使用）
    ja: "/pc/ja"
    en: "/pc/en"
  mode: "standard"  # または "cross_device"
  
alternate:
  enabled: true
  supported_langs: ["ja", "en"]
  base_device: "pc" # device_matrix:の導入でもう必要ない？
  device_matrix: ["pc", "mobile", "text"]    # ← ★追加ポイント
  region_map:
    ja: "ja-JP"
    en: "en-US"
  x_default: "/"
  mode: "cross_device"  # ← "standard" または "cross_device"
  
open_graph:
  enabled: true # ← OGタグ有効化
  locale_map:
    ja: "ja_JP"
    en: "en_US"

json_ld:
  enabled: true # ← 構造化データ出力をON
  entity_type: "Article"
  author_type: "Organization"
  ai_metadata:
    model: "ChatGPT-4o"
    processed_by: "OpenAI"
    content_type: "structured-blog"
  
twitter:
  enabled: true
  username: "@ai_chie"

favicon:
  enabled: true
  path: "/assets/favicon/"
  