defaults:
  description: "このサイトはAI・多言語・多端末に対応した情報発信を行うプロジェクトです。" # ← サイト全体の説明文
  image: "/assets/img/default-og-image.png" # ← SNSカードや構造化データのOG画像
  author: "AI-Chie Project" # ← schema.org用の著者名
  lang: "ja" # ← 未指定時の言語既定
  theme_color: "#ffffff"

robots:
  default: "index, follow"
  exclude_paths: # ← noindexにしたいパスのリスト
    - /search/
    - /404.html

# canonical.htmlのロジック制御用
canonical:
  enabled: true                # ← 全体ON/OFF。canonical出力を有効化。canonicalタグ全体の出力ON/OFF
  base_device: "pc"            # 正規URLとして使う device。canonicalを統一する対象の device（例: "pc"）。fallback時や旧モードでの基準device
  override_allowed: true       # Front Matterでの canonical_override を許可。page.canonical_override による上書きを許可。page.canonical_override を許可
  fallback_to_base: true       # per_lang にない言語は base_device/lang を使う。per_lang がない言語に fallback許容
  per_lang:                    # ← 言語別canonical正規パス。言語別canonicalルート（省略時は base_device 使用）。言語別canonicalパスマッピング
    ja: "/pc/ja"
    en: "/pc/en"
  mode: "priority"             # "standard"、"cross_device"、"priority"
  base_device_priority:        # device優先順位のリスト
    - pc
    - text
    - mobile
  
alternate:
  enabled: true                             # alternateタグ出力を有効にする
  supported_langs: ["ja", "en"]             # 対象となる言語
  base_device: "text"                         # 通常構成での言語パス構築に使われる基準device。（alternate.html 用）
  device_matrix: ["text", "mobile", "pc"]   # "cross_device" モード用（"priority" モードでは参照されない）。cross_device モードで交差対象となるdeviceの全リスト
  device_priority: ["text", "mobile", "pc"] # priorityモードで使用。言語ごとにこの順でdevice候補を探す。第1要素（例：text）が存在しない場合、第2候補（pc）へフォールバックする構成になっている
  region_map:                               # hreflangの地域指定変換。"ja-JP" や "en-US" はGoogle推奨形式
    ja: "ja-JP"
    en: "en-US"
  x_default: "/"                            # x-default用のURL。空文字やスラッシュでもOK。alternate_device_priority.html では "langs[0] × devices[0]" を使わず、明示指定が優先される
  mode: "priority"                          # ← "standard"（alternate.html）、"cross_device"（alternate_device_cross.html）、"priority"（alternate_device_priority.html）。使用するalternateテンプレートを決定するモード
  
open_graph:
  enabled: true # ← OGタグ有効化
  locale_map:
    ja: "ja_JP"
    en: "en_US"

json_ld:
  enabled: true # ← 構造化データ出力をON
  entity_type: "Article"
  author_type: "Organization"
  ai_metadata:
    model: "ChatGPT-4o"
    processed_by: "OpenAI"
    content_type: "structured-blog"
  
twitter:
  enabled: true
  username: "@ai_chie"

favicon:
  enabled: true
  path: "/assets/favicon/"
  