name: Generate Tag Counts

on:
  push:
    paths:
      - '_posts/**'
      - '_scripts/generate_tag_counts.rb'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Generate tag counts
        run: ruby _scripts/generate_tag_counts.rb

      - name: Commit and push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add _data/generated_tag_counts.yml
          git diff --quiet && git diff --staged --quiet || git commit -m "Update generated tag counts"
          git push
