name: Generate Gemfile.lock and Upload as Artifact

on:
  workflow_dispatch:

jobs:
  generate-lock:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Install bundler
        run: gem install bundler

      - name: Generate Gemfile.lock
        run: bundle lock

      - name: Upload Gemfile.lock as artifact
        uses: actions/upload-artifact@v4  # ← 修正ポイント
        with:
          name: Gemfile-lock
          path: Gemfile.lock
